### ISSUE TITLE
7. GitHub Actions - 一个完整的pull request的eslint检测的例子

### ISSUE THREAD

**Issue by taoliujun** [taoliujun/blog#36]
TODO

https://github.com/taoliujun/npm-packages/blob/test1/.github/workflows/check-pull-request.yml

**Comment by taoliujun** [comment]
# 初始化工作流

在项目中新建文件`.github/workflows/check-pull-request.yml`，内容如下：

```yaml
name: check pull request
run-name: 'check pull request #${{ github.event.pull_request.number }}'
on:
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    replyChecking:
        runs-on: ubuntu-latest
        steps:
            - run: echo 'job'

    init:
        runs-on: ubuntu-latest
        steps:
            - run: echo 'job'

    eslint:
        runs-on: ubuntu-latest
        needs: [init]
        steps:
            - run: echo 'job'

    typescript:
        runs-on: ubuntu-latest
        needs: [init]
        steps:
            - run: echo 'job'

    unitTest:
        runs-on: ubuntu-latest
        needs: [init]
        steps:
            - run: echo 'job'

    replyResult:
        runs-on: ubuntu-latest
        needs: [eslint, typescript, unitTest]
        steps:
            - run: echo 'job'
```

## name和run-name

给工作流命名为`check pull request`，它会出现在Actions页面的左侧菜单中。运行实例名为`check pull request #44`，出现在右侧的运行列表中。如图：

![](https://github.com/taoliujun/blog/assets/5689134/c1371ff2-8fc3-4e5b-8b60-3c572419938b)

`run-name`中的`${{ github.event.pull_request.number }}`是工作流的上下文，这里读取了上下文中的pr编号。

## on

`on`指定了工作流的触发条件，这里配置了在pull request创建、同步、重新打开的时候，触发该工作流。

## jobs

按照设想，需要定义几个工作，分别是：

-   replyChecking：回复用户正在检查中
-   init：初始化仓库，缓存依赖项
-   eslint：运行eslint检查
-   typescript：运行typescript检查
-   unitTest：运行单元测试
-   replyResult：回复用户检查结果

`job`是并行运行的，聪明如你肯定发现了，eslint、typescript、unitTest这三个工作里会涉及到安装npm依赖，所以它们最好在init工作后执行，确保依赖已经缓存了。其次，replyResult肯定要拿到eslint等工作的结果才能执行，所以使用了`needs`属性管理了它们的执行关系。

### runs-on

每个工作都运行在独立的容器中，github官方提供了windows、macos、linux多种容器，这里使用了ubuntu容器。

## 测试

发起一个pr，看到Actions页面出现了新的运行实例，点击进去，可以看到各个工作的运行情况和依赖关系：

![](https://github.com/taoliujun/blog/assets/5689134/2087f14f-1629-43e7-8683-cbfee49f22b6)

**Comment by taoliujun** [comment]
# replyChecking

在进行eslint检测之前，先在pr里回复`checking`，并且内容里带上拽酷炫的话。将replyChecking工作的配置改成如下：

```yaml
replyChecking:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
              ref: ${{github.head_ref}}
        - name: Get date time
          id: getDateTime
          run: echo "result=$(TZ=Asia/Shanghai date)" >> "$GITHUB_OUTPUT"
        - name: Create or update a comment
          uses: ./.github/actions/unique-comment
          with:
              uniqueIdentifier: ${{ github.workflow }}
              body: |
                  **Checking...**

                  ---

                  Commented by Action [${{github.workflow}}](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}}), last updated on ${{steps.getDateTime.outputs.result}}.
```

`steps`每一步称为**作业**，作业的`name`、`id`是可选的，`name`在Actions详情页面里会显示，更直观的看到作业的名称，推荐写上。

## Checkout

`uses`表示使用一个封装的工作或作业`actions/checkout@v4`，它用来拉取仓库。

> 同其他编程语言一样，重复的作业也可以封装起来。[actions市场](https://github.com/marketplace?type=actions)提供了很多。

`with`属性指定了该作业的输入参数，每个作业的参数不尽相同。

`ref`参数表示要拉取的分支，`${{github.head_ref}}`也是一个上下文，表示当前pr的源分支。


## Get Date time

这作业还写了`id`，表示该作业在该工作中的唯一标识，为什么要写呢？是为了下一步作业能根据`id`读取到它的`output`。

> **output**是工作流中非常重要的概念，它用于在作业之间、工作之间分享简单的数据。

`run`就是在容器中跑一个命令，这里跑了一个unix bash命令，将当前时间写入到`$GITHUB_OUTPUT`中，键名为`result`。

> `$GITHUB_OUTPUT`是工作流注入到容器中的一个路径，用于存放output。

## Create or update a comment

`uses`使用了本地的action，这个action是一个js脚本，用于创建或更新一个唯一回复，最后讲。

> 有时候，官方或市场的脚本并不能满足你的需要，就需要自己写一个脚本了。

同理，该action也有`with`属性，`uniqueIdentifier`是回复评论的唯一标识，`body`是回复的内容，内容使用了markdown语法，里面还涉及到上下文不一一细讲了。只说`${{steps.getDateTime.outputs.result}}`这个上下文表示获取getDateTime这个作业中，键名为`result`的值。

如果你不需要在内容里插入时间，那么上面的`Get Date time`作业就可以省略了。

## 测试

因为我已经有完整的代码了，所以运行后，pr中会有一个回复，如图：

![](https://github.com/taoliujun/blog/assets/5689134/42396a84-b798-4f4e-9f39-5bf92a8acb15)

**Comment by taoliujun** [comment]
# ./.github/actions/unique-comment

这是一个封装的javascript操作，用于对issue创建、更新唯一评论。

> 封装的操作也可以发布到github actions市场。

## 目录结构

创建目录`./.github/actions/unique-comment`，最终目录结构如下：

```bash
.
├── action.yml
├── config
│   └── webpack.config.js
├── dist
│   ├── index.js
│   └── index.js.LICENSE.txt
├── package.json
└── src
    └── index.js
```

## action.yml

这是action的配置文件，必须存在，内容如下：

```yaml
name: unique-comment
description: create or update a unique comment

runs:
    using: 'node20'
    main: './dist/index.js'

inputs:
    token:
        description: 'GitHub token'
        required: false
        default: ${{ github.token }}
    owner:
        description: 'Repository owner'
        required: false
        default: ${{ github.event.repository.owner.login }}
    repo:
        description: 'Repository name'
        required: false
        default: ${{ github.event.repository.name }}
    issue_number:
        description: 'Issue number'
        required: false
        default: ${{ github.event.number }}
    body:
        description: 'Comment body'
        required: false
    uniqueIdentifier:
        description: 'Unique identifier for comment'
        required: false
        default: 'unique-comment'
```

大部分属性不一一细讲了，都是简单的英文望文生义即可。

`runs`表示运行在`node20`环境下，入口文件为`./dist/index.js`。

`inputs`表示接受的参数，也就是之前提到的`with`属性里要输入的参数。用`required`表示是否必须传入，`default`表示默认值。

## src/index.js

为什么入口文件是`./dist/index.js`，而不是`src/index.js`呢？因为要引用一些官方提供的快捷操作github REST API的js包去操作issue评论(pull request也是一种issue)，最终打包后的文件才能在工作流中稳妥的运行。所以，写好`src/index.js`，再打包就行。

该文件代码如下：

```javascript
const core = require('@actions/core');
const github = require('@actions/github');

const main = async () => {
    const token = core.getInput('token');
    const owner = core.getInput('owner');
    const repo = core.getInput('repo');
    const issueNumber = core.getInput('issue_number');
    const uniqueIdentifier = `[^uniqueIdentifier]: ${core.getInput('uniqueIdentifier')}`;
    const body = `${core.getInput('body')}\n\n${uniqueIdentifier}`;

    core.debug(`uniqueIdentifier is ${uniqueIdentifier}`);

    const octokit = github.getOctokit(token);

    const comments = await octokit.rest.issues.listComments({
        owner,
        repo,
        issue_number: issueNumber,
    });

    const botComment = comments.data.find((v) => v.body.includes(uniqueIdentifier));

    if (botComment) {
        core.info('update comment successfully.');
        await octokit.rest.issues.updateComment({
            owner,
            repo,
            comment_id: botComment.id,
            body,
        });
    } else {
        core.info('create comment successfully.');
        await octokit.rest.issues.createComment({
            owner,
            repo,
            issue_number: issueNumber,
            body,
        });
    }
};

try {
    main();
} catch (err) {
    core.setFailed(err.message);
}
```

`@actions/core`和`@actions/github`是github官方提供的包，前者可以方便的读取入参等，后者可以方便的操作github REST API。

`main`函数的代码就是原生javascript，不一一解释了，主要通过`uniqueIdentifier`来判断是否发布过评论，如果是，就更新评论，否则就创建评论。

> markdown语法`[^uniqueIdentifier]`表示脚注，不会被渲染。

`core.setFailed(err.message);`表示运行错误的时候，抛出退出代码。

## config/webpack.config.js

打包用的，配置简单可用即可：

```javascript
module.exports = {
    mode: 'production',
    target: 'node20',
    entry: './src/index.js',
    output: {
        filename: 'index.js',
        clean: true,
    },
};
```

## package.json

```json
{
  "name": "unique-comment",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "webpack --config ./config/webpack.config.js"
  },
  "dependencies": {
    "@actions/core": "^1.10.1",
    "@actions/github": "^6.0.0"
  },
  "devDependencies": {
    "webpack": "^5.89.0",
    "webpack-cli": "^5.1.4"
  }
}
```

没啥好说的，列出了依赖项。和一个打包脚本。

## 测试

修改了`src/index.js`后记得`build`就行。记得将**dist**目录提交到github仓库。

**Comment by taoliujun** [comment]
# init

现在，开始搞正经的了。

先初始化项目，这个job的目的仅仅是为了缓存pnpm依赖项，如果你的项目的依赖项不经常更新，可以省略这个job，后续也不要`needs`这个job。

将init改成如下：

```yaml
init:
        runs-on: ubuntu-latest
        steps:
            - name: Init repo
              uses: actions/checkout@v4
              with:
                  ref: ${{github.head_ref}}

            - name: Init pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Init node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install
```

相信经过对之前的job的了解，这里的配置就看起来很简单了。

## Init pnpm

使用第三方action，安装pnpm@^8。

## Init node

`cache: 'pnpm'`指定缓存机制，它内部是利用了workflow的cache机制。

## Install dependencies

安装依赖项，触发缓存。
